export const SET_PRODUCTS = "SET_PRODUCTS"

export const SET_MENU = "SET_MENU"

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGIN_FAILURE = "LOGIN_FAILURE"